export const themes = {
  // Light Themes
  'soft-focus': {
    background: '#dfe6e6',
    typingBackground: '#e4f1ef',
    text: '#2e3440',
    borders: '#b0c4c4',
    defaultLetters: '#2e3440',
    correctLetter: '#3fa796',
    incorrectLetter: '#d47fa6',
    nextLetter: '#f0a202',
    spaces: '#c2b8a3',
    hover: '#8abbb3',
    clickedButtonBg: '#a8d4cc',
    clickedButtonText: '#20302e',
    isThemeLight: true
  },
  'sunrise-grove': {
    background: '#fff9f0',
    typingBackground: '#fffdf8',
    text: '#3a3d27',
    borders: '#cec1aa',
    defaultLetters: '#3a3d27',
    correctLetter: '#5caa72',
    incorrectLetter: '#e05d5d',
    nextLetter: '#d4a600',
    spaces: '#ffc46c',
    hover: '#bca86d',
    clickedButtonBg: '#f3c96b',
    clickedButtonText: '#3a2c00',
    isThemeLight: true
  },
  'crystal-lake': {
    background: '#e3f7f6',
    typingBackground: '#f4fcfc',
    text: '#284248',
    borders: '#b0dad7',
    defaultLetters: '#284248',
    correctLetter: '#34bfa1',
    incorrectLetter: '#f2778a',
    nextLetter: '#ffa15f',
    spaces: '#f8c97a',
    hover: '#7abfae',
    clickedButtonBg: '#91e0d3',
    clickedButtonText: '#18403a',
    isThemeLight: true
  },
  'lavender-bloom': {
    background: '#f8f4fa',
    typingBackground: '#fefbff',
    text: '#3e3b4f',
    borders: '#d3c0dc',
    defaultLetters: '#3e3b4f',
    correctLetter: '#84d3b1',
    incorrectLetter: '#eb799a',
    nextLetter: '#c99be0',
    spaces: '#cba1db',
    hover: '#c49fcf',
    clickedButtonBg: '#d4a6e8',
    clickedButtonText: '#3e2a4f',
    isThemeLight: true
  },
  'zen-dunes': {
    background: '#f9f5eb',
    typingBackground: '#fefbf3',
    text: '#3a382f',
    borders: '#dcd1ba',
    defaultLetters: '#3a382f',
    correctLetter: '#71b67a',
    incorrectLetter: '#d8654f',
    nextLetter: '#b08e33',
    spaces: '#f7b56d',
    hover: '#b7a179',
    clickedButtonBg: '#d8ae64',
    clickedButtonText: '#3a2f17',
    isThemeLight: true
  },
  // Dark Themes
  'night-lotus': {
    background: '#1c1b2a',
    typingBackground: '#242233',
    text: '#dde1eb',
    borders: '#3a3752',
    defaultLetters: '#dde1eb',
    correctLetter: '#70d1b4',
    incorrectLetter: '#f0758a',
    nextLetter: '#ffd447',
    spaces: '#f8a45d',
    hover: '#67a49f',
    clickedButtonBg: '#413c5e',
    clickedButtonText: '#eae6ff',
    isThemeLight: false
  },
  'shadow-fern': {
    background: '#1f2a23',
    typingBackground: '#26322c',
    text: '#d6e7db',
    borders: '#395145',
    defaultLetters: '#d6e7db',
    correctLetter: '#8ddcaa',
    incorrectLetter: '#e27979',
    nextLetter: '#ced44c',
    spaces: '#f8bb60',
    hover: '#7aa48c',
    clickedButtonBg: '#4e6f5b',
    clickedButtonText: '#e7fbee',
    isThemeLight: false
  },
  'muted-tides': {
    background: '#1d2326',
    typingBackground: '#282e31',
    text: '#d0dce6',
    borders: '#41545a',
    defaultLetters: '#d0dce6',
    correctLetter: '#7fc0e3',
    incorrectLetter: '#dd7790',
    nextLetter: '#ffd661',
    spaces: '#ffc37e',
    hover: '#7ea8be',
    clickedButtonBg: '#506a78',
    clickedButtonText: '#e6f5ff',
    isThemeLight: false
  },
  'charcoal-tea': {
    background: '#1c1a17',
    typingBackground: '#26231f',
    text: '#f3eee7',
    borders: '#3f3c37',
    defaultLetters: '#f3eee7',
    correctLetter: '#98d4a2',
    incorrectLetter: '#e37c66',
    nextLetter: '#e9c04a',
    spaces: '#f3a35f',
    hover: '#a2ae95',
    clickedButtonBg: '#665c4a',
    clickedButtonText: '#fff7e9',
    isThemeLight: false
  },
  'velvet-dusk': {
    background: '#221e29',
    typingBackground: '#2b2734',
    text: '#f2eff7',
    borders: '#4c4656',
    defaultLetters: '#f2eff7',
    correctLetter: '#a3bce3',
    incorrectLetter: '#df6e93',
    nextLetter: '#ffcc4d',
    spaces: '#f8a97c',
    hover: '#c3a9d6',
    clickedButtonBg: '#6f5c82',
    clickedButtonText: '#fbeaff',
    isThemeLight: false
  }
}

export const wordList = ["window","wave","throw","card","did","salt","officer","aside","swept","balance","write","replied","massage","ancient","standard",
  "led","night","gave","did","diagram","base","kill","possible","dot","will","describe","alone","tape","especially","observe","forget","original","occasionally",
  "we","national","milk","complete","typical","useful","stone","pleasant","seldom","port","strip","jungle","lungs","enjoy","visit","military","cup","youth",
  "excellent","hollow","note","before","verb","advice","importance","read","began","coffee","good","down","minute","studied","leg","wait","energy","bag","tears",
  "barn","smaller","forgot","below","modern","tail","instrument","form","paragraph","deer","independent","cast","unusual","complete","building","tiny","smile",
  "wear","mirror","had","choose","hit","mathematics","gave","desk","process","affect","protection","board","basic","war","instead","provide","home","concerned",
  "college","up","him","cap","today","sing","fully","environment","surprise","tropical","system","spoken","job","laugh","valuable","origin","possible","press",
  "walk","green","straw","nobody","listen","author","nuts","barn","cream","against","rope","nation","pay","something","bar","pipe","friendly","factory","chief",
  "cave","white","single","beauty","stone","heard","load","noise","forgot","rope","anyway","tank","quickly","hunter","myself","aloud","element","ran","saw",
  "operation","engineer","sum","other","got","whether","president","its","led","field","cup","operation","differ","rising","stove","customs","fair","image",
  "born","community","lie","spirit","machine","swung","most","whale","shut","you","winter","beneath","silent","continued","late","very","operation","coming",
  "same","fewer","five","roar","shall","moment","divide","fierce","seed","successful","cap","locate","out","history","bark","first","serious","rain","birthday",
  "done","tribe","seen","moving","mission","gold","seed","smooth","future","practical","tune","electricity","construction","development","pull","why","sold",
  "split","various","barn","try","title","enough","biggest","mud","seed","means","brought","present","might","himself","depend","pale","harder","slightly",
  "dollar","next","storm","smooth","stomach","combination","species","previous","feet","land","graph","rush","doll","noun","science","fat","average","song",
  "twelve","outline","struck","round","grow","said","hot","balance","carried","southern","per","operation","donkey","air","poor","dangerous","direction",
  "explain","greater","nine","construction","plural","future","member","canal","sick","store","save","pile","pupil","level","properly","everybody","speak",
  "statement","dance","successful","mix","proper","consonant","teeth","numeral","slope","mill","uncle","deal","dirt","driven","closer","outline","who",
  "rain","name","factor","molecular","signal","explanation","pound","needle","date","dot","metal","slight","needed","bear","wash","air","usual","birthday",
  "entire","stand","atmosphere","chemical","tales","whom","special","forward","replied","section","sick","ship","couple","throughout","orange","card","simplest",
  "income","plate","rest","check","men","mood","promised","whether","progress","so","air","clearly","anyone","monkey","nuts","without","meat","engineer","city",
  "earlier","library","hardly","bad","sets","knowledge","you","here","wheat","wrong","explanation","thumb","variety","fire","five","according","condition",
  "market","particularly","enough","instant","planet","definition","pile","truck","automobile","continent","failed","there","tales","rays","factory","think",
  "tears","monkey","doing","function","century","inch","ground","danger","wooden","wagon","appearance","own","stems","entire","nice","must","death","opposite",
  "lion","shut","leg","fifth","shelter","soon","building","lamp","war","substance","bow","article","whole","dig","kept","pilot","select","mud","write","never",
  "replace","monkey","thou","spend","easier","horn","fire","perfect","pictured","along","number","captain","port","came","traffic","daily","sitting","bark",
  "good","farm","nest","tube","sweet","snow","boat","famous","trail","wide","week","cast","tube","difficult","taken","dollar","blind","grandfather","particularly",
  "tip","strength","during","elephant","larger","manner","grade","previous","whatever","father","vast","band","story","flower","egg","clean","living","forest",
  "chest","vote","imagine","growth","pocket","grown","rose","silent","cabin","except","president","figure","future","club","said","flat","found","far","other",
  "massage","tried","tin","carry","hurt","half","face","herd","led","noun","sense","sheep","shinning","drew","castle","wear","government","remember","just",
  "roll","control","worse","highest","that","attention","flies","iron","rock","highway","industry","swam","somewhere","run","swimming","industry","began","win",
  "funny","area","widely","jack","higher","full","guess","transportation","secret","even","lonely","section","now","copy","born","greater","driven","fewer",
  "label","cat","fewer","except","she","guess","length","only","material","got","moon","luck","badly","summer","occur","policeman","color","vegetable","fuel",
  "if","hundred","carefully","curve","soon","receive","stronger","fair","atom","adventure","nature","total","list","throughout","mass","baseball","pass",
  "have","pile","walk","operation","higher","mother","ancient","function","bat","pull","share","colony","take","goose","sent","bet","quiet","cattle","shadow",
  "inside","especially","both","halfway","lost","red","care","thy","closely","heavy","type","would","broken","gentle","strength","shoot","faster","cap","not",
  "secret","color","prove","pink","whether","structure","arrive","worth","solve","mysterious","guard","just","universe","key","outline","behavior","known",
  "station","lay","rabbit","smell","poem","could","me","around","until","room","must","machine","many","fort","condition","sit","recall","final","standard",
  "stick","dish","statement","treated","visit","it","frighten","stronger","rubber","vegetable","add","three","dozen","fear","port","half","even","pattern",
  "throat","pound","path","copy","move","price","immediately","luck","return","coffee","purple","safe","alphabet","plates","skin","article","central","bell",
  "fought","sheet","cell","hunter","easy","explain","market","environment","environment","prepare","chamber","while","break","black","beside","wrapped","good",
  "select","stand","balance","better","by","worse","movement","recent","later","exactly","private","trick","consist","stranger","individual","value","drove",
  "story","dog","ourselves","worth","come","value","together","natural","is","vowel","eleven","swung","ancient","population","edge","material","mind","major",
  "down","save","age","seed","doll","vote","minute","club","lift","happily","knowledge","special","last","blanket","struggle","lucky","organized","rising",
  "purple","do","card","principal","attention","triangle","trip","scientist","express","stairs","world","taste","shoe","four","with","garage","congress",
  "sink","pride","surprise","table","substance","enter","against","language","train","expect","or","ill","earlier","learn","lot","directly","rain","above",
  "fourth","transportation","speech","breakfast","shot","individual","sell","men","unhappy","raw","during","middle","visit","became","another","funny","jack",
  "warn","usual","arm","sign","answer","sold","influence","reason","rate","blank","against","buy","sick","effect","nearest","hard","recently","stop","verb",
  "electric","lead","flower","selection","about","food","balloon","poem","cool","conversation","win","lead","buy","wish","hung","story","lucky","know","radio",
  "police","joined","corn","closely","art","only","neighbor","habit","fell","get","in","moving","pile","wash","symbol","wet","population","ranch","search",
  "column","supply","office","mirror","owner","beginning","rising","table","smoke","chart","audience","master","needle","arrangement","tea","center","heading",
  "stick","everything","potatoes","danger","generally","tie","somehow","forest","exchange","produce","careful","factory","musical","package","whether","contrast",
  "original","principle","twelve","universe","day","pony","ahead","fair","engine","good","fighting","cut","division","whole","point","gentle","visitor","meant",
  "gradually","star","guess","cookies","rush","account","queen","worried","complex","motion","practical","shallow","keep","week","crowd","we","gulf","swept",
  "free","science","great","excellent","sides","pay","least","by","appropriate","pilot","leaf","low","nobody","bank","farther","cutting","familiar","broad","line",
  "examine","thick","stove","longer","road","huge","sweet","charge","airplane","torn","worse","empty","saved","string","captured","among","similar","lucky",
  "tail","happen","rather","willing","fully","fruit","number","crop","interest","birth","energy","different","plant","store","soft","easier","lady","describe",
  "move","off","fine","never","meant","stomach","per","dinner","speech","amount","into","building","hunter","automobile","forty","late","orbit","stared",
  "chapter","identity","color","determine","heart","remarkable","look","sat","phrase","whenever","safe","coffee","spell","hurt","chain","mathematics","chose",
  "spent","tune","compare","cost","begun","allow","suggest","such","into","remain","knife","develop","package","north","grow","low","pleasure","small","court",
  "wool","mental","percent","night","its","note","eager","season","sing","accurate","stems","while","radio","best","wonderful","pile","weak","declared","dinner",
  "victory","coat","trap","page","white","tool","town","needs","comfortable","ran","parallel","class","song","them","during","seven","pride","dance","trunk",
  "dawn","chart","previous","exercise","few","equally","properly","charge","tent","tonight","shoe","animal","vegetable","tell","will","dream","putting","found",
  "ordinary","among","music","onto","add","becoming","spoken","throughout","men","student","independent","drink","growth","vapor","brass","coffee","camera",
  "factor","surface","pony","fire","deal","manner","service","aware","serve","were","mood","stretch","later","mouth","sum","handle","lying","game","yet","give",
  "bag","victory","higher","lion","needs","world","dead","funny","chicken","enjoy","relationship","house","satellites","dot","handle","foreign","tell","thrown",
  "past","pond","process","income","reader","strike","tune","explore","massage","perfect","entirely","needs","large","wore","face","slow","object","pony",
  "usually","milk","wonder","eat","specific","successful","loud","pay","chosen","steady","major","during","whether","cream","loud","way","split","object",
  "design","pay","push","will","shells","leader","cookies","rapidly","animal","beauty","class","prize","noun","jet","rain","struck","vertical","beauty","sheet",
  "men","coal","title","belong","hungry","dawn","carried","dream","important","cross","alike","recently","indicate","quiet","shot","discussion","appropriate",
  "heart","properly","thus","because","better","mysterious","minute","rather","whose","scared","twelve","sell","children","model","declared","somehow","where",
  "aid","ourselves","somewhere","occasionally","knew","window","count","zero","steam","properly","east","dry","money","depth","bus","until","stove","no","trick",
  "weak","locate","flight","ruler","let","egg","ill","whispered","after","sang","separate","mirror","sometime","newspaper","yourself","guard","my","task",
  "pleasant","deeply","crack","upper","nation","tin","near","small","own","almost","slide","frequently","concerned","brother","faster","journey","ask","society",
  "business","sort","country","rhythm","double","dig","work","possible","shape","whose","earlier","clothing","explain","stared","process","liquid","grow","kept",
  "aware","cry","relationship","hardly","pick","difficulty","gulf","attention","living","load","any","nine","women","has","crack","goes","symbol","lift","alone",
  "split","market","roar","rough","worry","ought","voice","gentle","dirty","powder","eat","great","author","per","opinion","something","beauty","let","religious",
  "account","rocket","slept","range","coat","stove","pipe","religious","these","snow","duty","soldier","circus","fell","ordinary","adjective","mirror","opinion",
  "there","space","given","plan","ever","sweet","main","not","himself","dinner","condition","burn","space","while","frozen","truck","hello","along","grass",
  "left","concerned","process","magic","ourselves","neck","triangle","lying","money","pocket","melted","depth","slabs","powder","directly","slightly","purple",
  "edge","structure","through","fine","supper","thou","love","direction","fly","line","title","shorter","total","song","characteristic","leaving","everybody",
  "standard","basic","over","open","safety","belong","shout","information","television","nuts","more","ground","every","along","plus","sleep","product","own",
  "merely","thee","measure","smell","sets","treated","chance","fellow","completely","sand","identity","up","over","brass","are","broke","manner","equal","eye",
  "nearby","stomach","mad","lamp","spin","began","definition","thousand","sight","hill","clothing","black","society","running","salmon","plates","fresh","sudden",
  "importance","appearance","win","more","draw","friendly","shoot","worth","atom","knew","person","doctor","period","felt","musical","settle","make","then",
  "obtain","carbon","nice","question","us","hurt","company","feature","respect","danger","strip","movie","lips","tears","behind","into","journey","people","are",
  "hang","ran","protection","graph","with","build","hard","land","among","stone","stomach","village","nuts","each","brown","bag","practical","strange","alike",
  "create","ancient","weight","atomic","energy","case","carry","detail","barn","could","dug","thread","rain","step","minute","gain","lucky","serve","neighborhood",
  "dish","show","whose","creature","tank","fed","declared","time","dirty","continent","afraid","labor","indicate","somebody","clearly","bottle","bag","function",
  "some","raw","to","fought","nose","determine","vertical","due","reader","seat","given","entire","jack","previous","mistake","continent","roof","poetry","book",
  "service","shine","grew","agree","section","can","cream","sea","circus","dark","met","jet","camera","service","drop","owner","dress","half","left","there","talk",
  "control","character","grandfather","extra","needle","paint","mathematics","across","brave","tonight","push","slope","flight","avoid","gravity","distance",
  "never","school","small","everything","younger","slept","task","system","copper","good","consist","reader","experiment","nose","lack","character","recall",
  "valuable","strength","sick","reader","poet","tide","fourth","shoe","experiment","unknown","escape","burn","death","actual","scientist","stick","law","tape",
  "twice","sister","rear","pupil","exact","agree","familiar","widely","triangle","saved","here","explanation","main","low","eat","method","end","fear","mistake",
  "service","wonder","service","saddle","coach","jungle","future","tip","driver","chief","rose","ask","ball","feel","industrial","cutting","world","road","son",
  "living","belt","daughter","record","solve","what","uncle","soon","floating","mighty","all","dog","drew","into","night","rocket","do","calm","spring","lying",
  "studying","fog","driven","sick","pan","principal","newspaper","milk","rise","date","flies","order","floating","environment","block","play","kitchen","mirror",
  "weak","table","eventually","married","water","lay","more","principal","favorite","win","customs","call","shoulder","phrase","special","pass","board","report",
  "think","direct","against","track","blank","when","son","remain","stock","tree","dig","eat","gather","would","work","place","rising","lips","sad","must","done",
  "program","decide","ground","furniture","camp","failed","throw","first","carry","habit","vessels","different","duck","kids","divide","these","club","troops",
  "chance","look","familiar","strike","plain","evening","broad","fat","classroom","habit","already","up","production","already","available","actually","troops",
  "halfway","shot","zoo","between","us","open","palace","flower","whistle","heart","solution","written","treated","hot","package","troops","popular","income",
  "first","track","chicken","lonely","native","bare","easy","cry","drive","onto","supply","cowboy","view","damage","stiff","division","shoulder","pipe","sudden",
  "open","voyage","primitive","rubber","poem","too","smile","money","made","beside","generally","magic","map","built","smile","exciting","like","light",
  "properly","duck","after","serve","post","dirty","community","them","drink","mice","eleven","vast","youth","slave","steel","sand","plain","have","numeral",
  "flies","football","itself","refer","teeth","finest","chair","green","piece","chose","scientist","port","heavy","satisfied","molecular","anyway","path",
  "instrument","shells","replied","creature","magic","today","crop","screen","difference","pretty","particularly","certainly","spring","structure","forty",
  "chicken","turn","chemical","route","terrible","equally","leaving","describe","earn","left","camera","thee","pilot","brief","due","daily","brass","shot",
  "stopped","beat","prove","east","open","electric","captured","animal","person","blow","heart","arrangement","rough","dollar","duck","hunter","date","birds",
  "thick","stop","contrast","noon","getting","triangle","larger","elephant","sense","jump"
];